<?php

namespace app\admin\controller;

use app\common\controller\Base;
use think\Session;

class Login extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //登录页
    public function login()
    {
        if (!empty(Session::get('adminUser'))) {
            $this->redirect('admin/Index/index');
        }
        return $this->fetch();
    }

    //执行登录
    public function doLogin()
    {
        $passport = $this->getVal($this->rqData, 'passport');
        $password = $this->getVal($this->rqData, 'password');
        if ($passport !== 'admin' || $password != 'admin') {
            $this->error('登录失败');
        }
        //模拟登录成功
        $adminUser = [
            'id' => 1,
            'passport' => 'admin',
            'username' => '本地管理员Jcai',
            'group_id' => 2,
            'last_ip' => '192.168.5',
            'last_login' => time(),
        ];
        Session::set('adminUser', $adminUser);
        $this->redirect(url('admin/Index/index'));
    }

    //登出
    public function logout()
    {
        Session::delete('adminUser');
        $this->redirect('admin/Login/login');
        exit;
    }


}