<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/4
 * Time: 11:30
 */

namespace app\admin\controller;


use app\common\controller\Base;

class Open extends Base
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    //欢迎页
    public function welcome()
    {
        return $this->fetch();
    }

}