<?php

namespace app\common\model;

use think\Model;

class AdminBase extends Model
{
    //
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}
