<?php

namespace app\common\model;

use think\Model;

class WapBase extends Model
{
    //支持登录渠道
    protected $oauthArr = array('weixin','qq','alipay');
    //用户授权渠道
    protected $oauthType = '';
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

}
